# Generated by Django 2.1.1 on 2019-06-07 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import payInt.models
import payInt.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeesMatched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc_name', models.CharField(default='', help_text='TimeClick Employee Name', max_length=100)),
                ('qb_name',
                 models.CharField(blank=True, default='', help_text='QuickBooks Employee Name', max_length=100)),
            ],
            options={
                'ordering': ['-owner'],
            },
        ),
        migrations.CreateModel(
            name='PayrollCenterUsers',
            fields=[
                ('row_id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(blank=True, help_text='Companies name', max_length=100)),
                ('timer_header', models.FileField(blank=True, storage=payInt.storage.OverwriteStorage(),
                                                  upload_to=payInt.models.user_directory_path)),
                ('employee_list', models.FileField(blank=True, storage=payInt.storage.OverwriteStorage(),
                                                   upload_to=payInt.models.user_directory_path)),
                ('payroll_items', models.FileField(blank=True, storage=payInt.storage.OverwriteStorage(),
                                                   upload_to=payInt.models.user_directory_path)),
                ('timeclick_extract_file', models.FileField(blank=True, storage=payInt.storage.OverwriteStorage(),
                                                            upload_to=payInt.models.user_directory_path)),
                ('export', models.FileField(blank=True, storage=payInt.storage.OverwriteStorage(),
                                            upload_to=payInt.models.user_directory_path)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-owner'],
            },
        ),
        migrations.CreateModel(
            name='PayrollItemsMatched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc_item', models.CharField(default='', help_text='TimeClick Item Name', max_length=100)),
                ('qb_item', models.CharField(blank=True, default='', help_text='QuickBooks Item Name', max_length=100)),
                ('owner',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payInt.PayrollCenterUsers')),
            ],
            options={
                'ordering': ['-owner'],
            },
        ),
        migrations.AddField(
            model_name='employeesmatched',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payInt.PayrollCenterUsers'),
        ),
    ]
